backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "assets/images"

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - file: "index.html"
        label: "Home Page"
        name: "index"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }

      - file: "about.html"
        label: "About Us Page"
        name: "about"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }

      - file: "services.html"
        label: "Services Page"
        name: "services"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }

      - file: "contact.html"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }

  - name: "gallery"
    label: "Gallery Images"
    folder: "assets/images"
    create: true
    fields:
      - { label: "Image Title", name: "title", widget: "string" }
      - { label: "Image File", name: "image", widget: "image" }