backend:
  name: git-gateway
  branch: main

# Where uploaded image files are stored
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "gallery_page"
    label: "Gallery Management"
    files:
      - file: "data/gallery.json"
        label: "Photo Gallery"
        name: "gallery_data"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            summary: "{{fields.alt}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description / Alt Text", name: "alt", widget: "string", required: false }