backend:
  name: git-gateway
  branch: main

# Path configuration for site media and admin logo
media_folder: "assets/images"
public_folder: "/assets/images"
logo_url: /assets/images/logo.jpeg

# CMS Collections Configuration
collections:
  - name: "gallery"
    label: "Gallery Images"
    folder: "assets/images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }